#!/usr/bin/env bash

if [ ! -f ./config.env ]; then
    echo ".env not found"
    exit
fi

docker network create slbnetwork

docker volume create postgresdata
docker volume create slbdata

docker run -d --name spacexlaunchbot-postgres --restart unless-stopped \
    --env-file $(pwd)/config.env \
    -v $(pwd)/pg-create.sh:/docker-entrypoint-initdb.d/pg-create.sh \
    -v postgresdata:/var/lib/postgresql/data \
    --network slbnetwork \
    postgres

docker run -d --name spacexlaunchbot --restart unless-stopped \
    -v slbdata:/docker-volume \
    --network slbnetwork \
    --env-file $(pwd)/config.env \
    psidex/spacexlaunchbot

docker run -d --name spacexlaunchbot-webserver --restart unless-stopped \
    --network slbnetwork \
    --env-file $(pwd)/config.env \
    psidex/spacexlaunchbot-webserver

# To connect to another network, proxynet for example:
# docker network connect proxynet spacexlaunchbot-webserver
