#!/bin/bash

#
# Dump the SLB database to ./dumps
# Provide "c" arg (e.g. bash ./backup c) to compress after dump
# pg_dump: https://stackoverflow.com/a/29913462/6396652
#

set -e
source config.env
set -x

mkdir -p "./dumps"

DUMP_FILE="./dumps/$(date +"%Y%m%d_%H%M%S").sql"
DUMP_FILE_TGZ="$DUMP_FILE.tar.gz"

docker exec -t slb-$SLB_DB_HOST-1 pg_dump \
  -U $POSTGRES_USER --dbname=$POSTGRES_DB \
  --column-inserts --data-only \
  >"$DUMP_FILE"

if [ "$1" == "c" ]; then
  tar -cvzf "$DUMP_FILE_TGZ" "$DUMP_FILE"
  rm "$DUMP_FILE"
fi
