#!/usr/bin/env bash
set -ex

# https://stackoverflow.com/a/29913462/6396652
# Interactive psql: docker exec -it slb-postgres psql -U slb --dbname=spacexlaunchbot

docker exec -t slb-postgres pg_dump \
  -U slb --dbname=spacexlaunchbot \
  >"dump_$(date +%d-%m-%Y"_"%H_%M_%S).sql"
