#!/usr/bin/env bash
set -ex

if [ ! -f ./config.env ]; then
  echo "config.env not found"
  exit
fi
source config.env

# https://stackoverflow.com/a/29913462/6396652

docker exec -t slb-$SLB_DB_HOST-1 pg_dump \
  -U $POSTGRES_USER --dbname=$POSTGRES_DB \
  >"dump_$(date +%d-%m-%Y"_"%H_%M_%S).sql"
